### PR TITLE
update 

### PR DESCRIPTION
**Pull request by ritikavar**
## nice to work

### CODE REVIEW

**Comment by tushar5526** [comment]
@ritikvar we don't use the master branch for development. Make sure you make a new branch and then work on it.

**Comment by ritikavar** [comment]
How to change branch?

**Comment by tushar5526** [comment]
Most open-source projects have contribution guidelines in their repository, we have it too [here](https://github.com/The-Codesis/Hello-World/blob/master/README.md)
Always read the guidelines, then start contributing.

**Comment by CapTen101** [comment]
closing this one. new one is opened #15

**Pull request closed without merging**
